### ISSUE TITLE
Non-ASCII characters & SyntaxError

### ISSUE THREAD

**Issue by terokorp** [boarpig/dyfi.py#2]
### First error:

`SyntaxError: Non-ASCII character '\xc3' in file ./dyfi.py on line 21, but no encoding declared`

Solved by adding this to line2:
`# -*- coding: utf-8 -*-`
### Second error:

```
--add lippua käytetty
Käyttäjä: firstname.lastname@gmail.com
Traceback (most recent call last):
  File "/usr/bin/dyfi.py", line 122, in <module>
    add_host()
  File "/usr/bin/dyfi.py", line 87, in add_host
    user = input("Käyttäjä: ")
  File "<string>", line 1
    firstname.lastname@gmail.com
                      ^ <- that points @
SyntaxError: invalid syntax
```
### System:

Debian Jessie (8.5)
Python 2.7.9
LANG: fi_FI.UTF-8

**Comment by boarpig** [comment]
Fixed
